#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
# shellcheck source=/dev/null
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

# Customize to your needs...

#DEFAULT_USER='tprice'
# Source local sensitive exports
# shellcheck source=/dev/null
source ~/.zlocalenv

# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)
# Add extra completions
fpath=(/usr/local/share/zsh-completions $fpath)
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi
# Advanced autocomplete
autoload -U compinit && compinit -i

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

setopt NO_HUP

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB

# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM

# Aliases
eval "$(hub alias -s)"
alias g="git"
alias pull='git pull'
alias push='git push'
alias pushf='git push --force-with-lease'
alias status='git status'
alias sort=gsort
#alias ls='gls --color=always'
alias ls='exa'
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias lslsa='ls -lsa'
alias lsl='ls -l'
alias lsld='ls -ld'
alias lah='ls -lah'

# kubectl
alias k='kubectl'

export EDITOR="/usr/bin/vi"
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"
export LANG="en_US"
export LC_ALL="en_US.UTF-8"
export LESS_TERMCAP_md="$ORANGE"
export MANPAGER="less -X"
#export GREP_OPTIONS="--color=auto"

export LS_COLORS='di=1;34:ln=35:so=32:pi=0;33:ex=32:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=1;34:ow=1;34:'
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "^R" history-incremental-pattern-search-backward
bindkey "^S" history-incremental-pattern-search-forward
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey -e
bindkey "[C" forward-word
bindkey "[D" backward-word

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space

eval "$(direnv hook zsh)"
eval "$(gdircolors -b ~/.dircolors)"
eval "$(thefuck --alias)"

# shellcheck source=/dev/null
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
#source /usr/local/share/zsh/site-functions/_awless

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/bin/google-cloud-sdk/path.zsh.inc' ]; then source '/usr/local/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/bin/google-cloud-sdk/completion.zsh.inc' ]; then source '/usr/local/bin/google-cloud-sdk/completion.zsh.inc'; fi
export CLOUDSDK_PYTHON=/usr/bin/python

# shellcheck source=/dev/null
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$HOME/.yarn/bin:$PATH:/Users/tprice/Library/Python/3.7/bin"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#alias node='unalias node ; unalias npm ; nvm use default ; node $@'
#alias npm='unalias node ; unalias npm ; nvm use default ; npm $@'

function gobin() {
  command="$1"
  shift
  args="$*"
  eval "${GOPATH}/bin/${command} ${args}"
}

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
